export @symbol("SDL_IsTablet"                             ) fn IsTablet() SDL_bool;
export @symbol("SDL_OnApplicationWillTerminate"           ) fn OnApplicationWillTerminate() void;
export @symbol("SDL_OnApplicationDidReceiveMemoryWarning" ) fn OnApplicationDidReceiveMemoryWarning() void;
export @symbol("SDL_OnApplicationWillResignActive"        ) fn OnApplicationWillResignActive() void;
export @symbol("SDL_OnApplicationDidEnterBackground"      ) fn OnApplicationDidEnterBackground() void;
export @symbol("SDL_OnApplicationWillEnterForeground"     ) fn OnApplicationWillEnterForeground() void;
export @symbol("SDL_OnApplicationDidBecomeActive"         ) fn OnApplicationDidBecomeActive() void;
